In [2]:
#导入库 
from bs4 import BeautifulSoup
import requests
import time 
import datetime
import smtplib

In [22]:
#和网站建立连接
URL='https://www.amazon.com/dp/B07BDWD8B7'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/129.0.0.0 Safari/537.36','Accept-Language': 'en-US,en;q=0.9','Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'}

page=requests.get(URL,headers=headers)

soup1=BeautifulSoup(page.content,"html.parser")

soup2=BeautifulSoup(soup1.prettify(),"html.parser")

title=soup2.select_one('#productTitle').get_text(strip=True)

price=soup2.select_one('.a-price .a-offscreen').get_text(strip=True)

print(title)
print(price)

Amazon Basics Retractable Ballpoint Pens with Comfortable Grip for Smooth Writing, Black, Note-Taking, Office and School Supplies, 12-Pack
$9.60

In [24]:
price=price.strip()[1:]
title=title.strip()

print(title)
print(price)

Amazon Basics Retractable Ballpoint Pens with Comfortable Grip for Smooth Writing, Black, Note-Taking, Office and School Supplies, 12-Pack
9.60

In [29]:
today=datetime.date.today()
print(today)

2026-10-03

In [30]:
import csv

header=['Title','Price','Date']
data=[title,price,today]

#把数据导入到csv文件(覆盖)
#with open('AmazonWebScraperDataset.csv','w',newline='',encoding='UTF8') as f:
    #writer=csv.writer(f)
    #writer.writerow(header)
    #writer.writerow(data)

In [31]:
import pandas as pd
df=pd.read_csv(r"D:\ana_jupyter\Web Scarping in Python\AmazonWebScraperDataset.csv")
df

                                               Title  Price        Date
0  Amazon Basics Retractable Ballpoint Pens with ...    9.6  2026-10-03

In [ ]:
#把数据导入到csv文件(添加)
with open('AmazonWebScraperDataset.csv','a+',newline='',encoding='UTF8') as f:
    writer=csv.writer(f)
    writer.writerow(data)

In [34]:
def check_price():
    URL='https://www.amazon.com/dp/B07BDWD8B7'

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/129.0.0.0 Safari/537.36','Accept-Language': 'en-US,en;q=0.9','Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'}

    page=requests.get(URL,headers=headers)

    soup1=BeautifulSoup(page.content,"html.parser")

    soup2=BeautifulSoup(soup1.prettify(),"html.parser")

    title=soup2.select_one('#productTitle').get_text(strip=True)

    price=soup2.select_one('.a-price .a-offscreen').get_text(strip=True)

    price=price.strip()[1:]
    title=title.strip()

    import datetime
    today=datetime.date.today()

    import csv
    header=['Title','Price','Date']
    data=[title,price,today]

    with open('AmazonWebScraperDataset.csv','a+',newline='',encoding='UTF8') as f:
        writer=csv.writer(f)
        writer.writerow(data)

    #if(price<8):
        #send_mail()

In [35]:
#每隔一段时间新增监控数据
while(True):
    check_price()
    time.sleep(86400)

KeyboardInterrupt:

In [36]:
import pandas as pd
df=pd.read_csv(r"D:\ana_jupyter\Web Scarping in Python\AmazonWebScraperDataset.csv")
df

                                               Title  Price        Date
0  Amazon Basics Retractable Ballpoint Pens with ...    9.6  2026-10-03
1  Amazon Basics Retractable Ballpoint Pens with ...    9.6  2026-10-03
2  Amazon Basics Retractable Ballpoint Pens with ...    9.6  2026-10-03
3  Amazon Basics Retractable Ballpoint Pens with ...    9.6  2026-10-03

In [38]:
#定义函数监测数据变化并发送邮件提醒

# def send_mail():
#     server = smtplib.SMTP_SSL('smtp.gmail.com',465)
#     server.ehlo()
#     #server.starttls()
#     server.ehlo()
#     server.login('xxx@gmail.com','xxxxxxxxxxxxxx')
    
#     subject = "XXX" #标题
#     body = "xxxxxx"#内容
   
#     msg = f"Subject: {subject}\n\n{body}"
    
#     server.sendmail(
#         'xxx@xxx.com',#发件人邮箱
#        #'xxx@xxx.com',#收件人
#         msg
     
#     )